spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supero
    username: username
    password: password
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: create
logging:
  level:
    org.springframework: WARN
    com.suntech.project.mapper.UserMapper: DEBUG
